# Generated by Django 5.1.5 on 2025-04-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('firebase_uid', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'kullanicilar',
            },
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('kac_puan', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urunler',
            },
        ),
        migrations.CreateModel(
            name='KirliBolgeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('cop_turu', models.TextField(blank=True, null=True)),
                ('cop_miktari', models.IntegerField(blank=True, null=True)),
                ('temizleme_suresi', models.TimeField(blank=True, null=True)),
                ('durum', models.TextField(blank=True, null=True)),
                ('paylasim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'kirli_bolgeler',
            },
        ),
        migrations.CreateModel(
            name='Etkinlikler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etkinlik_title', models.TextField(blank=True, null=True)),
                ('etkinlik_decription', models.TextField(blank=True, null=True)),
                ('etkinlik_yeri', models.TextField(blank=True, null=True)),
                ('etkinlik_date', models.DateTimeField(blank=True, null=True)),
                ('puan', models.IntegerField(blank=True, null=True)),
                ('kontenjan', models.IntegerField(blank=True, null=True)),
                ('ucret', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('orgranizator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'etkinlikler',
            },
        ),
        migrations.CreateModel(
            name='EtinklikKatilimlari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('katilim_tarihi', models.DateField(blank=True, null=True)),
                ('katildi_mi', models.BooleanField(blank=True, null=True)),
                ('puan_verildimi', models.BooleanField(blank=True, db_column='puan_verildiMi', null=True)),
                ('etkinlik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.etkinlikler')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etinklikkatilimlari_user_set', to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'etinklik_katilimlari',
            },
        ),
        migrations.CreateModel(
            name='Cleanups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ilkfoto', models.TextField(blank=True, db_column='ilkFoto', null=True)),
                ('son_foto', models.TextField(blank=True, null=True)),
                ('kazanilan_puan', models.IntegerField(blank=True, null=True)),
                ('adminonayladimi', models.BooleanField(blank=True, db_column='adminOnayladiMi', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanups_area_set', to='trashure.kirlibolgeler')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'cleanUps',
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profil_aciklamasi', models.TextField(blank=True, null=True)),
                ('rozetler', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('haftalik_aktiflik', models.IntegerField(blank=True, null=True)),
                ('friends_count', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserRewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('satinalmatarihi', models.DateTimeField(blank=True, db_column='satinAlmaTarihi', null=True)),
                ('harcana_puan', models.IntegerField(blank=True, null=True)),
                ('durum', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrewards_product_set', to='trashure.urunler')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar')),
            ],
            options={
                'db_table': 'user_rewards',
            },
        ),
    ]
