# Generated by Django 5.1.5 on 2025-04-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashure', '0002_alter_kullanicilar_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirlibolgeler',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='trashure.kullanicilar', to_field='firebase_uid'),
        ),
    ]
