# Generated by Django 5.1.5 on 2025-04-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashure', '0003_alter_kirlibolgeler_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirlibolgeler',
            name='paylasim_tarihi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kirlibolgeler',
            name='temizleme_suresi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
